### ISSUE TITLE
change folder structure

### ISSUE THREAD

**Issue by tanaypratap** [sohamsshah/next-chakra-redux-toolkit-starter#1]
src 
  /pages
           Login.tsx
           Signup.tsx
           ForgotPassword.tsx
           
           // Check how to name auth/protected pages in NextJS
           // Omkar: How to protect pages in NextJS ; Create an issue for Omkar on main repo
           
           // Make Pages for other features as well. keep those empty
           
  /features
        /submission
                
        /interview
        /admission         
        
  /components // Sushil 
       Button.tsx
       Card.tsx
       Banner.tsx
       Input.tsx // if there's anything extra
       
   

 chakra-theme.config.js
        
  // Check how page related components can be named in a folder
  /page-components

**Comment by sohamsshah** [comment]
close via https://github.com/neogcamp/platform-93by4/pull/10
